---
title: "Assignment 6"
format: gfm
editor: visual
---

```{r}
#| echo: false

library(tidyverse)
library(knitr)
```

## Exercise 1. Tibble and Data Import

1.1

```{r}
tribble(
  ~a, ~b, ~c,
  #--|--|----
  1, 2.1, "apple",
  2, 3.2, "orange"
)

tibble(
  a = 1:2,
  b = 2.1:3.2,
  c = c("apple", "orange")
)
```

1.2

```{r}
data2 <- read.csv("https://raw.githubusercontent.com/nt246/NTRES-6100-data-science/master/datasets/dataset2.txt",
                  header = FALSE)
colnames(data2) <- c("Name", "Weight", "Price")
data2
```

1.3

```{r}
data3 <- read.csv("https://raw.githubusercontent.com/nt246/NTRES-6100-data-science/master/datasets/dataset3.txt",
                   header = TRUE,   # There's a header line after the metadata
  sep = ";",               # Columns separated by semicolons
  quote = "/",             # Text enclosed in slashes
  na.strings = c("?", "Not Available"),  # Handle missing values
  skip = 2,                # Skip first two metadata lines
  stringsAsFactors = FALSE
)
data3
```
